# Generated by Django 3.0.4 on 2020-03-21 23:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200321_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wiki',
            new_name='Wikis',
        ),
    ]
